name: Build and Deploy Frontier Website
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout front-end repo @ frontier branch
        uses: actions/checkout@v3
        with:
          repository: osmosis-labs/osmosis-frontend
          ref: frontier

      - name: Install and Build 🔧 # This will create version inside the 'build' folder.
        run: |
          yarn
          yarn build:css && yarn build 
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: prod
